name: design_patterns
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  dio: ^5.5.0+1
  faker_dart: ^0.2.2
  firebase_analytics: ^11.3.4
  firebase_core: ^3.7.0
  firebase_remote_config: ^5.1.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.1
  riverpod_annotation: ^2.3.5
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
