// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3QgqQodYIHO3RziDwneDleH-hnS37P5c',
    appId: '1:916332478403:web:c1aa1e12fd8b74f9338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    authDomain: 'flutter-notifications-90077.firebaseapp.com',
    storageBucket: 'flutter-notifications-90077.firebasestorage.app',
    measurementId: 'G-312EX91DX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZoUTs_oWlNw0E8e_pR8Q-E4YD5oMIKw',
    appId: '1:916332478403:android:1f056d93904e0ea3338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    storageBucket: 'flutter-notifications-90077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVROziIMDLYn9JAg21962CzC1TBsNssd0',
    appId: '1:916332478403:ios:8a2d4db50aa86701338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    storageBucket: 'flutter-notifications-90077.firebasestorage.app',
    androidClientId: '916332478403-ibubmkiuecqjklvi2jbvl8ci7b8v9rt8.apps.googleusercontent.com',
    iosClientId: '916332478403-668hbfngedvh3ut70dmddf31c7ul6r2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.designPatterns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVROziIMDLYn9JAg21962CzC1TBsNssd0',
    appId: '1:916332478403:ios:8a2d4db50aa86701338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    storageBucket: 'flutter-notifications-90077.firebasestorage.app',
    androidClientId: '916332478403-ibubmkiuecqjklvi2jbvl8ci7b8v9rt8.apps.googleusercontent.com',
    iosClientId: '916332478403-668hbfngedvh3ut70dmddf31c7ul6r2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.designPatterns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0YPjq44hmd1OIY4eA_iGPaTp8THccDCk',
    appId: '1:916332478403:web:4549060b2251874a338776',
    messagingSenderId: '916332478403',
    projectId: 'flutter-notifications-90077',
    authDomain: 'flutter-notifications-90077.firebaseapp.com',
    storageBucket: 'flutter-notifications-90077.firebasestorage.app',
    measurementId: 'G-LS90ES94JM',
  );
}
